Update patch set 1
Patch Set 1:

This change breaks the build for me, we must be doing things differently:

ERROR: /home/mfick/gerrit/plugins/batch/BUILD:3:1: Building plugins/batch/libbatch__plugin-class.jar (23 source files) failed (Exit 1)
plugins/batch/src/main/java/com/googlesource/gerrit/plugins/batch/ssh/MergeChangeCommand.java:58: error: [strict] Using type com.google.gerrit.util.cli.Options from an indirect dependency (TOOL_INFO: "//gerrit-util-cli:cli"). See command below **
  @Inject @Options public MergeStrategyOption strategy;
           ^
 ** Please add the following dependencies: 
  //gerrit-util-cli:cli to //plugins/batch:batch__plugin 
 ** You can use the following buildozer command: 
buildozer 'add deps //gerrit-util-cli:cli' //plugins/batch:batch__plugin

Patch-set: 1
CC: Gerrit User 1010013 <1010013@173816e5-2b9a-37c3-8a2e-48639d4f1153>